services:
  yourprojectname.webapi:
    image: ${DOCKER_REGISTRY-}yourprojectnamewebapi
    build:
      context: .
      dockerfile: YourProjectName.WebApi/Dockerfile
    ports:
      - 8080:8080
      - 8081:8081
  postgres-compose:
    image: postgres:17
    container_name: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    # volumes:
    #   - ./.containers/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
  redis-compose:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
  keycloak-compose:
    image: quay.io/keycloak/keycloak:26.2.5
    container_name: keycloak
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    command: start-dev --import-realm
    ports:
      - 5000:8080
    volumes:
      - ./containers/keycloak:/opt/keycloak/data/import