services:
  yourprojectname.webapi:
    image: ${DOCKER_REGISTRY-}yourprojectnamewebapi
    build:
      context: .
      dockerfile: YourProjectName.WebApi/Dockerfile
    ports:
      - 8080:8080
      - 8081:8081
  postgres-compose:
    image: postgres:17
    container_name: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  redis-compose:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379